# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=100, unique=True),
        ),
    ]
