# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogue',
            table='Catalogue',
        ),
    ]
