# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'categorie', 'verbose_name_plural': 'categorie'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'guide', 'verbose_name_plural': 'guide'},
        ),
        migrations.AlterModelOptions(
            name='magasin',
            options={'verbose_name': 'magasin', 'verbose_name_plural': 'magasin'},
        ),
        migrations.AlterModelOptions(
            name='offre',
            options={'verbose_name': 'offre', 'verbose_name_plural': 'offre'},
        ),
        migrations.AlterModelTable(
            name='caracteristique',
            table='caracteristique',
        ),
        migrations.AlterModelTable(
            name='catalogue',
            table='catalogue',
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categorie',
        ),
        migrations.AlterModelTable(
            name='guide',
            table='guide',
        ),
        migrations.AlterModelTable(
            name='imagesproduit',
            table='images_produit',
        ),
        migrations.AlterModelTable(
            name='magasin',
            table='magasin',
        ),
        migrations.AlterModelTable(
            name='offre',
            table='offre',
        ),
        migrations.AlterModelTable(
            name='produit',
            table='produit',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='promotion',
        ),
        migrations.AlterModelTable(
            name='souscategorie',
            table='sous_categorie',
        ),
    ]
