# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171028_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='titre',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
