# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171105_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='date_debut',
            field=models.DateField(auto_now=True),
        ),
    ]
