# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_promotion_date_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='nom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
